/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiPluginCkeditor5 from "strapi-plugin-ckeditor5/strapi-admin";
import navigation from "strapi-plugin-navigation/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "color-picker": colorPicker,
    documentation: documentation,
    graphql: graphql,
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-plugin-ckeditor5": strapiPluginCkeditor5,
    navigation: navigation,
  },
});
